---
- hosts: all
  tasks:
    - name: change permissions
      file:
        name: permissions
        path: /var/lib/tomcat9/conf/webapps
        mode: 0777
        state: present
        
    - name: deploy code
      copy:
        src: java-example.war
        dest: /var/lib/tomcat9/conf/webapps/java-example.war

