---
- hosts: all
  become: yes 

  tasks:
    - name: change permissions
      file:
        path: /var/lib/tomcat9
        mode: 0777
        recurse: yes
        state: directory

    - name: deploy code
      copy:
        src: java-example.war
        dest: /var/lib/tomcat9/conf/webapps/java-example.war
        
    - name: Restart Tomcat Service
      service:
        name: tomcat9
        state: restarted

